### ISSUE TITLE
Create Structure of Patients in headerfile

### ISSUE THREAD

**Issue by ShettyGaneshprasad** [ShettyGaneshprasad/SDLC_27_PatientVaccineManagement#54]
int uniq_id;
    char firstname[101];
    char lastname[101];
    char aadhar_num[21];
    float height;
    float weight;
    int age;
    char date_of_vaccine[13];
    insured insurance;
    vaccine shot;
    struct patient *next;

**Comment by AnandBotkule** [comment]
i have done this
